BEGIN;

SET TIME ZONE 'Asia/Hong_Kong';

CREATE TABLE IF NOT EXISTS schema_migration (
    filename VARCHAR(255) PRIMARY KEY,
    checksum CHAR(64) NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_schema_migration_checksum
        CHECK (checksum ~ '^[0-9a-f]{64}$')
);

CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(50),
    avatar VARCHAR(255),
    role VARCHAR(30) NOT NULL DEFAULT 'admin',
    status BOOLEAN NOT NULL DEFAULT TRUE,
    token_version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_user_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS site_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name VARCHAR(50) NOT NULL,
    site_description VARCHAR(255),
    publish_url VARCHAR(255),
    background_type VARCHAR(20) NOT NULL DEFAULT 'color',
    background_color VARCHAR(30) NOT NULL DEFAULT '#050505',
    background_image VARCHAR(500),
    mobile_background_image VARCHAR(500),
    font_color VARCHAR(30) NOT NULL DEFAULT '#ffffff',
    background_effect BOOLEAN NOT NULL DEFAULT FALSE,
    music_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    music_url VARCHAR(500),
    subscribe_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    top_content_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    message_text VARCHAR(100),
    version INTEGER NOT NULL DEFAULT 0,
    install_completed_at TIMESTAMP,
    install_instance_id UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_site_config_background_type
        CHECK (background_type IN ('color', 'image'))
);

CREATE TABLE IF NOT EXISTS nav_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    icon VARCHAR(100),
    sort_order INTEGER NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_nav_category_sort
    ON nav_category (sort_order, id);

CREATE TABLE IF NOT EXISTS nav_bookmark (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    url VARCHAR(500) NOT NULL,
    icon VARCHAR(255),
    description VARCHAR(255),
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_recommend BOOLEAN NOT NULL DEFAULT FALSE,
    is_external BOOLEAN NOT NULL DEFAULT TRUE,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_nav_bookmark_category
        FOREIGN KEY (category_id) REFERENCES nav_category (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_nav_bookmark_category_sort
    ON nav_bookmark (category_id, sort_order, id);

CREATE TABLE IF NOT EXISTS search_engine (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    icon VARCHAR(255),
    search_url VARCHAR(500) NOT NULL,
    placeholder VARCHAR(100),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_search_engine_one_visible_default
    ON search_engine ((1))
    WHERE is_default IS TRUE AND visible IS TRUE;

CREATE INDEX IF NOT EXISTS idx_search_engine_visible_sort
    ON search_engine (visible, sort_order, id);

CREATE TABLE IF NOT EXISTS custom_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    url VARCHAR(500) NOT NULL,
    position VARCHAR(20) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_custom_link_position
        CHECK (position IN ('header', 'footer'))
);

CREATE INDEX IF NOT EXISTS idx_custom_link_position_sort
    ON custom_link (position, sort_order, id);

CREATE OR REPLACE FUNCTION nav_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at THEN
        NEW.updated_at = CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sys_user_updated_at ON sys_user;
CREATE TRIGGER trg_sys_user_updated_at
    BEFORE UPDATE ON sys_user
    FOR EACH ROW EXECUTE FUNCTION nav_set_updated_at();

DROP TRIGGER IF EXISTS trg_site_config_updated_at ON site_config;
CREATE TRIGGER trg_site_config_updated_at
    BEFORE UPDATE ON site_config
    FOR EACH ROW EXECUTE FUNCTION nav_set_updated_at();

DROP TRIGGER IF EXISTS trg_nav_category_updated_at ON nav_category;
CREATE TRIGGER trg_nav_category_updated_at
    BEFORE UPDATE ON nav_category
    FOR EACH ROW EXECUTE FUNCTION nav_set_updated_at();

DROP TRIGGER IF EXISTS trg_nav_bookmark_updated_at ON nav_bookmark;
CREATE TRIGGER trg_nav_bookmark_updated_at
    BEFORE UPDATE ON nav_bookmark
    FOR EACH ROW EXECUTE FUNCTION nav_set_updated_at();

DROP TRIGGER IF EXISTS trg_search_engine_updated_at ON search_engine;
CREATE TRIGGER trg_search_engine_updated_at
    BEFORE UPDATE ON search_engine
    FOR EACH ROW EXECUTE FUNCTION nav_set_updated_at();

DROP TRIGGER IF EXISTS trg_custom_link_updated_at ON custom_link;
CREATE TRIGGER trg_custom_link_updated_at
    BEFORE UPDATE ON custom_link
    FOR EACH ROW EXECUTE FUNCTION nav_set_updated_at();

-- Administrator credentials are never stored in SQL. A fresh deployment uses
-- the token-protected web installer by default; explicit legacy bootstrap may
-- create the first user from ADMIN_USERNAME / ADMIN_PASSWORD instead.

INSERT INTO site_config (
    id, site_name, site_description, publish_url, background_type,
    background_color, font_color, message_text
) VALUES (
    1, 'XY 导航', '简洁、快速、可自定义的网址导航', '/', 'color',
    '#050505', '#ffffff', '今天也要高效地找到想去的地方'
) ON CONFLICT DO NOTHING;

INSERT INTO nav_category (id, name, icon, sort_order, visible) VALUES
    (1, '常用', '✦', 10, TRUE),
    (2, '设计', '◈', 20, TRUE),
    (3, '开发', '⌘', 30, TRUE),
    (4, '云服务', '☁', 40, TRUE),
    (5, '影音', '♪', 50, TRUE),
    (6, '阅读', '书', 60, TRUE)
ON CONFLICT DO NOTHING;

INSERT INTO nav_bookmark (
    id, category_id, name, url, icon, description, sort_order,
    is_recommend, is_external, visible
) VALUES
    (1, 1, '百度', 'https://www.baidu.com/', NULL, '中文搜索引擎', 10, TRUE, TRUE, TRUE),
    (2, 1, 'Bing', 'https://www.bing.com/', NULL, '微软搜索引擎', 20, FALSE, TRUE, TRUE),
    (3, 2, 'Figma', 'https://www.figma.com/', NULL, '协作式界面设计工具', 10, TRUE, TRUE, TRUE),
    (4, 3, 'GitHub', 'https://github.com/', NULL, '代码托管与协作平台', 10, TRUE, TRUE, TRUE),
    (5, 3, 'MDN', 'https://developer.mozilla.org/', NULL, 'Web 开发文档', 20, FALSE, TRUE, TRUE),
    (6, 4, 'Cloudflare', 'https://www.cloudflare.com/', NULL, '网络与安全服务', 10, FALSE, TRUE, TRUE),
    (7, 5, '哔哩哔哩', 'https://www.bilibili.com/', NULL, '视频社区', 10, FALSE, TRUE, TRUE),
    (8, 6, '知乎', 'https://www.zhihu.com/', NULL, '中文问答社区', 10, FALSE, TRUE, TRUE)
ON CONFLICT DO NOTHING;

INSERT INTO search_engine (
    id, name, icon, search_url, placeholder, is_default, sort_order, visible
) VALUES
    (1, '百度', NULL, 'https://www.baidu.com/s?wd={keyword}', '百度一下，你就知道', TRUE, 10, TRUE),
    (2, 'Bing', NULL, 'https://www.bing.com/search?q={keyword}', '使用 Bing 搜索', FALSE, 20, TRUE),
    (3, 'Google', NULL, 'https://www.google.com/search?q={keyword}', '使用 Google 搜索', FALSE, 30, TRUE)
ON CONFLICT DO NOTHING;

INSERT INTO custom_link (id, title, url, position, sort_order, visible) VALUES
    (1, '管理后台', '/admin', 'header', 10, TRUE),
    (2, '关于本站', 'https://xydh.fun/', 'footer', 10, TRUE)
ON CONFLICT DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('public.sys_user', 'id')::regclass,
    COALESCE(MAX(id), 1),
    COUNT(*) > 0
) FROM sys_user;
SELECT setval(
    pg_get_serial_sequence('public.site_config', 'id')::regclass,
    COALESCE(MAX(id), 1),
    COUNT(*) > 0
) FROM site_config;
SELECT setval(
    pg_get_serial_sequence('public.nav_category', 'id')::regclass,
    COALESCE(MAX(id), 1),
    COUNT(*) > 0
) FROM nav_category;
SELECT setval(
    pg_get_serial_sequence('public.nav_bookmark', 'id')::regclass,
    COALESCE(MAX(id), 1),
    COUNT(*) > 0
) FROM nav_bookmark;
SELECT setval(
    pg_get_serial_sequence('public.search_engine', 'id')::regclass,
    COALESCE(MAX(id), 1),
    COUNT(*) > 0
) FROM search_engine;
SELECT setval(
    pg_get_serial_sequence('public.custom_link', 'id')::regclass,
    COALESCE(MAX(id), 1),
    COUNT(*) > 0
) FROM custom_link;

INSERT INTO schema_migration (filename, checksum)
VALUES
    (
        '20260812_0001_postgresql_baseline.sql',
        '006e38274447656002de06d53f7d4154ba80984388dcb26d1223e636dfce91a6'
    ),
    (
        '20260814_0002_web_install_state.sql',
        '7347e9e96d3c2347e1067624b786437f3b509e9d7e7614e773c6b1e067596d86'
    ),
    (
        '20260815_0003_install_instance_identity.sql',
        '17df5851046d9a79eb24923b4760f8d0440b15a9a68d1609e2bffe2f1ce280fb'
    )
ON CONFLICT (filename) DO NOTHING;

COMMIT;
