CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(50),
    avatar VARCHAR(255),
    role VARCHAR(30) NOT NULL DEFAULT 'admin',
    status BOOLEAN NOT NULL DEFAULT TRUE,
    token_version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS schema_migration (
    filename VARCHAR(255) PRIMARY KEY,
    checksum CHAR(64) NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS site_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name VARCHAR(50) NOT NULL,
    site_description VARCHAR(255),
    publish_url VARCHAR(255),
    background_type VARCHAR(20) NOT NULL DEFAULT 'color',
    background_color VARCHAR(30) NOT NULL DEFAULT '#050505',
    background_image VARCHAR(500),
    mobile_background_image VARCHAR(500),
    font_color VARCHAR(30) NOT NULL DEFAULT '#ffffff',
    background_effect BOOLEAN NOT NULL DEFAULT FALSE,
    music_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    music_url VARCHAR(500),
    subscribe_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    top_content_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    message_text VARCHAR(100),
    version INTEGER NOT NULL DEFAULT 0,
    install_completed_at TIMESTAMP,
    install_instance_id UUID NOT NULL DEFAULT RANDOM_UUID(),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_site_config_background_type
        CHECK (background_type IN ('color', 'image'))
);

CREATE TABLE IF NOT EXISTS nav_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    icon VARCHAR(100),
    sort_order INTEGER NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_nav_category_sort
    ON nav_category(sort_order, id);

CREATE TABLE IF NOT EXISTS nav_bookmark (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    url VARCHAR(500) NOT NULL,
    icon VARCHAR(255),
    description VARCHAR(255),
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_recommend BOOLEAN NOT NULL DEFAULT FALSE,
    is_external BOOLEAN NOT NULL DEFAULT TRUE,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_nav_bookmark_category
        FOREIGN KEY (category_id) REFERENCES nav_category(id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_nav_bookmark_category_sort
    ON nav_bookmark(category_id, sort_order, id);

CREATE TABLE IF NOT EXISTS search_engine (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    icon VARCHAR(255),
    search_url VARCHAR(500) NOT NULL,
    placeholder VARCHAR(100),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    default_guard SMALLINT GENERATED ALWAYS AS (
        CASE WHEN is_default AND visible THEN 1 ELSE NULL END
    ),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_search_engine_one_visible_default UNIQUE(default_guard)
);
CREATE INDEX IF NOT EXISTS idx_search_engine_visible_sort
    ON search_engine(visible, sort_order, id);

CREATE TABLE IF NOT EXISTS custom_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    url VARCHAR(500) NOT NULL,
    position VARCHAR(20) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_custom_link_position CHECK (position IN ('header', 'footer'))
);
CREATE INDEX IF NOT EXISTS idx_custom_link_position_sort
    ON custom_link(position, sort_order, id);

MERGE INTO schema_migration (filename, checksum) KEY(filename) VALUES
    (
        '20260812_0001_postgresql_baseline.sql',
        '006e38274447656002de06d53f7d4154ba80984388dcb26d1223e636dfce91a6'
    ),
    (
        '20260814_0002_web_install_state.sql',
        '7347e9e96d3c2347e1067624b786437f3b509e9d7e7614e773c6b1e067596d86'
    ),
    (
        '20260815_0003_install_instance_identity.sql',
        '17df5851046d9a79eb24923b4760f8d0440b15a9a68d1609e2bffe2f1ce280fb'
    );
